name-template: 'v$RESOLVED_VERSION 🚀'
tag-template: 'v$RESOLVED_VERSION'

version-resolver:
  major:
    labels: ['major']
  minor:
    labels: ['feat']
  patch:
    labels: ['fix']
  default: patch

categories:
  - title: '🚀 Features'
    labels: ['feat']
  - title: '🐛 Bug Fixes'
    labels: ['fix']
  - title: '🛠 Refactors'
    labels: ['refactor']
  - title: '🧹 Chore & Maintenance'
    labels: ['chore', 'build']
  - title: '📝 Documentation'
    labels: ['docs']
  - title: '🔥 Removed'
    labels: ['removed']

change-template: '- $TITLE ($CHANGESET) by @$AUTHOR'

template: |
  ## What's new?
  $CHANGES
