branches:
  - "master"

plugins:
  - "@semantic-release/commit-analyzer"
  - - "@semantic-release/release-notes-generator"
    - preset: "conventionalcommits"
      presetConfig:
        types:
          - type: "feat"
            section: "🚀 Features"
          - type: "fix"
            section: "🐛 Bug Fixes"
          - type: "chore"
            section: "🧰 Maintenance"
          - type: "refactor"
            section: "🛠 Refactors"
          - type: "docs"
            section: "📝 Documentation"
          - type: "perf"
            section: "⚡ Performance"
          - type: "removed"
            section: "🔥 Removed"
  - "@semantic-release/github"