plugins {
    id 'base'
}

group = 'me.marioogg.command'
version = '2.1'

def versionString = version.toString()
def isBeta = versionString.contains('-b')
def isSnapshot = versionString.endsWith('SNAPSHOT')

def publishTarget = isBeta
        ? 'https://maven.marioogg.dev/repository/private'
        : isSnapshot
            ? 'https://maven.marioogg.dev/repository/snapshots'
            : 'https://maven.marioogg.dev/repository/releases'

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'

    group = rootProject.group
    version = rootProject.version

    repositories {
        mavenCentral()
        maven { url 'https://maven.marioogg.dev/repository/public/' }
    }

    dependencies {
        if (project.name != 'common') {
            api project(':common')
        }

        implementation("org.apache.logging.log4j:log4j-core:3.0.0-beta3")
        api "com.google.guava:guava:33.5.0-jre"
        compileOnly 'org.projectlombok:lombok:1.18.36'
        annotationProcessor 'org.projectlombok:lombok:1.18.36'

        testImplementation platform('org.junit:junit-bom:5.10.0')
        testImplementation 'org.junit.jupiter:junit-jupiter'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
        withJavadocJar()
        withSourcesJar()
    }

    test {
        useJUnitPlatform()
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                from components.java
                artifactId = "${rootProject.name}-${project.name}"
            }
        }

        repositories {
            maven {
                url = uri(publishTarget)
                credentials {
                    username = System.getenv('MAVEN_USERNAME')
                    password = System.getenv('MAVEN_PASSWORD')
                }
            }
        }
    }
}
